/*
Note: For this question, we used the data generated by Q9_datagenerated.sql
 */

SELECT * FROM Comment LIMIT 10;

SELECT * FROM CommentReaction LIMIT 10;

SELECT * FROM Conversation LIMIT 10;

SELECT * FROM Follows LIMIT 10;

SELECT * FROM Location LIMIT 10;

SELECT * FROM Message LIMIT 10;

SELECT * FROM Organization LIMIT 10;

SELECT * FROM PartOf LIMIT 10;

SELECT * FROM Post LIMIT 10;

SELECT * FROM PostReaction LIMIT 10;

SELECT * FROM School LIMIT 10;

SELECT * FROM StudyPeriod LIMIT 10;

SELECT * FROM Users LIMIT 10;

SELECT * FROM Wall LIMIT 10;

SELECT * FROM WorkPeriod LIMIT 10;

SELECT * FROM WorkPlace LIMIT 10;